### ISSUE TITLE
Flaky integration tests

### ISSUE THREAD

**Issue by LorenzoBettini** [xtext/xtext-reference-projects#465]
By looking at the typical and consistent failure of integration tests, and looking at the screenshot, the problem is in the deletion of projects:

```
Tests run: 12, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 606.2 s <<< FAILURE! -- in org.eclipse.xtext.swtbot.tests.XtextNewProjectWizardTest
org.eclipse.xtext.swtbot.tests.XtextNewProjectWizardTest.simpleXtextProject -- Time elapsed: 42.38 s
org.eclipse.xtext.swtbot.tests.XtextNewProjectWizardTest.xtextProject_webIntegration_withGradle_nested -- Time elapsed: 78.71 s <<< ERROR!
org.eclipse.swtbot.swt.finder.widgets.TimeoutException: Timeout after: 10000 ms.: The shell Shell with text {Delete Resources} did not close.
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:522)
	at org.eclipse.swtbot.swt.finder.SWTBot.waitUntil(SWTBot.java:1)
	at org.eclipse.xtext.swtbot.testing.internal.XtextSWTBot.waitUntil(XtextSWTBot.java:1)
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:496)
	at org.eclipse.swtbot.swt.finder.SWTBot.waitUntil(SWTBot.java:1)
	at org.eclipse.xtext.swtbot.testing.internal.XtextSWTBot.waitUntil(XtextSWTBot.java:1)
	at org.eclipse.xtext.swtbot.testing.internal.XtextSWTBotShell.waitUntilClosed(XtextSWTBotShell.java:45)
	at org.eclipse.xtext.swtbot.testing.api.PackageExplorerAPI.deleteMavenProject(PackageExplorerAPI.java:145)
	at org.eclipse.xtext.swtbot.testing.api.PackageExplorerAPI.deleteMavenProjects(PackageExplorerAPI.java:130)
	at org.eclipse.xtext.swtbot.testing.api.PackageExplorerAPI.deleteAllProjects(PackageExplorerAPI.java:110)
	at org.eclipse.xtext.swtbot.testing.api.EclipseAPI.deleteAllProjects(EclipseAPI.java:73)
	at org.eclipse.xtext.swtbot.tests.XtextNewProjectWizardTest.tearDown(XtextNewProjectWizardTest.java:53)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunAfters.invokeMethod(RunAfters.java:46)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.eclipse.swtbot.swt.finder.junit.SWTBotJunit4ClassRunner.runChild(SWTBotJunit4ClassRunner.java:75)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.swtbot.swt.finder.junit.SWTBotJunit4ClassRunner.run(SWTBotJunit4ClassRunner.java:60)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:316)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:240)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:214)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:155)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.apache.maven.surefire.api.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:137)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:148)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:88)
	at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.run(OsgiSurefireBooter.java:140)
	at org.eclipse.tycho.surefire.osgibooter.AbstractUITestApplication.runTests(AbstractUITestApplication.java:51)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Testable.lambda$0(E4Testable.java:79)
	at java.base/java.lang.Thread.run(Thread.java:840)

org.eclipse.xtext.swtbot.tests.XtextNewProjectWizardTest.xtextProject_forEclipse_withTesting_withMaven -- Time elapsed: 119.3 s
org.eclipse.xtext.swtbot.tests.XtextNewProjectWizardTest.xtextProject_webIntegration_withLSPRegular -- Time elapsed: 46.26 s
org.eclipse.xtext.swtbot.tests.XtextNewProjectWizardTest.xtextProject_webIntegration_withMaven_nested -- Time elapsed: 49.81 s
org.eclipse.xtext.swtbot.tests.XtextNewProjectWizardTest.xtextProject_forEclipse -- Time elapsed: 19.59 s
org.eclipse.xtext.swtbot.tests.XtextNewProjectWizardTest.xtextProject_forEclipse_withTesting -- Time elapsed: 21.16 s
org.eclipse.xtext.swtbot.tests.XtextNewProjectWizardTest.xtextProject_webIntegration_withMaven_plain -- Time elapsed: 47.45 s
org.eclipse.xtext.swtbot.tests.XtextNewProjectWizardTest.xtextProject_webIntegration_withGradle_plain -- Time elapsed: 30.32 s
org.eclipse.xtext.swtbot.tests.XtextNewProjectWizardTest.simpleXtextProject_withMaven -- Time elapsed: 57.08 s
org.eclipse.xtext.swtbot.tests.XtextNewProjectWizardTest.xtextProject_forEclipse_withTesting_withGradle -- Time elapsed: 46.54 s
org.eclipse.xtext.swtbot.tests.XtextNewProjectWizardTest.xtextProject_webIntegration_withLSPFatJar -- Time elapsed: 46.61 s

Results:

Errors: 
  XtextNewProjectWizardTest.tearDown:53 » Timeout Timeout after: 10000 ms.: The shell Shell with text {Delete Resources} did not close.

Tests run: 12, Failures: 0, Errors: 1, Skipped: 0
```

It looks like the problem is the parent project of a maven projects...

Personally, I prefer to delete projects programmatically instead of simulating the operations with SWTBot.

I can try to do that, @cdietrich wdt?

**Comment by cdietrich** [comment]
No the problem is the gradle import and then run tests does not work 
See

**Comment by cdietrich** [comment]
https://github.com/eclipse-xtext/xtext/issues/2849

**Comment by cdietrich** [comment]
The one in your stacktrace I quite never see on maven projects

**Comment by cdietrich** [comment]
The delete problem is as far as i remember just a follow up for that

**Comment by LorenzoBettini** [comment]
The build is green though with my PR.

**Comment by LorenzoBettini** [comment]
Maybe the Gradle problem was fixed upstream in the meantime

**Comment by LorenzoBettini** [comment]
Moreover, the linked xtext issue refers to an old configuration we got rid of.
